# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - feature/*

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Cache@2
    inputs:
      key: 'gradle | "$(Agent.OS)" | **/build/**'
      restoreKeys: 'gradle | "$(Agent.OS)"'
      path: '.gradle'
    displayName: 'Cache dependencies and build directory'

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: "17"
      jdkArchitectureOption: "x64"
      jdkSourceOption: "PreInstalled"
    displayName: "Setup JDK 17"

  - task: Gradle@3
    inputs:
      workingDirectory: ""
      gradleWrapperFile: "gradlew"
      gradleOptions: "-Xmx3072m"
      options: "-Pvaadin.productionMode --stacktrace --info"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.17"
      jdkArchitectureOption: "x64"
      publishJUnitResults: true
      testResultsFiles: "**/TEST-*.xml"
      tasks: "build"
    displayName: "Gradle Build"

  - script: |
      curl https://cli-assets.heroku.com/install.sh | sh
      echo $(HEROKU_API_KEY) | heroku login --interactive
#      heroku login -i
#      heroku container:login
    displayName: 'Install and authenticate with Heroku CLI'

  - script: heroku deploy:jar --app fortyloveapp build/libs/fortylove-0.0.1-SNAPSHOT.jar
    env:
      HEROKU_EMAIL: $(HEROKU_EMAIL)
      HEROKU_API_KEY: $(HEROKU_API_KEY)
    displayName: 'Deploy to Heroku'

#  - task: PowerShell@2
#    inputs:
#      targetType: 'inline'
#      script: |
#        git checkout $(Build.SourceBranchName)
#        git remote add heroku https://heroku:$(HEROKU_API_KEY)@git.heroku.com/fortyloveapp.git
#        git push heroku $(Build.SourceBranchName)
#    displayName: "Deploy to Heroku"

#  - task: netplus-vsextension-heroku@1
#    inputs:
#      herokuApplicationName: "fortyloveapp"
#      herokuApiKey: "$(HEROKU_API_KEY)"
#    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
#    displayName: "Deploy to Heroku"

