trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: "windows-latest" # Task: PushToHeroku needs windows-vmImage

steps:
  - task: PushToHeroku@0
    inputs:
      ApiKey: "$(HEROKU_API_KEY)"
      AppName: "$(HEROKU_APP_NAME_PRODUCTION)"
      PushRoot: "$(System.DefaultWorkingDirectory)"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    displayName: "Deploy to Heroku Production"

  - task: PushToHeroku@0
    inputs:
      ApiKey: "$(HEROKU_API_KEY)"
      AppName: "$(HEROKU_APP_NAME_DEVELOP)"
      PushRoot: "$(System.DefaultWorkingDirectory)"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    displayName: "Deploy to Heroku Develop"