trigger:
  branches:
    include:
      - feature/*

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Cache@2
    inputs:
      key: "gradle | \"$(Agent.OS)\" | **/build/**"
      restoreKeys: "gradle | \"$(Agent.OS)\""
      path: ".gradle"
    displayName: "Cache dependencies and build directory"

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: "17"
      jdkArchitectureOption: "x64"
      jdkSourceOption: "PreInstalled"
    displayName: "Setup JDK 17"

  - task: Gradle@3
    inputs:
      workingDirectory: ""
      gradleWrapperFile: "gradlew"
      gradleOptions: "-Xmx3072m"
      options: "-Pvaadin.productionMode --stacktrace --info"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.17"
      jdkArchitectureOption: "x64"
      publishJUnitResults: true
      testResultsFiles: "**/TEST-*.xml"
      tasks: "build"
    env:
      SPRING_DATASOURCE_URL: "$(SPRING_DATASOURCE_URL)"
      SPRING_DATASOURCE_USERNAME: "$(SPRING_DATASOURCE_USERNAME)"
      SPRING_DATASOURCE_PASSWORD: "$(SPRING_DATASOURCE_PASSWORD)"
    displayName: "Gradle Build"
    
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/build/libs/fortylove-0.0.1-SNAPSHOT.jar'
      ArtifactName: 'fortyloveapp'
      publishLocation: 'Container'