# Azure Pipelines YAML file
# Check for more info https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema-reference
trigger:
  branches:
    include:
    - feature/*
  paths:
    include:
    - plantuml/*

pool:
  vmImage: windows-latest

workspace:
  clean: all

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0

- task: PowerShell@2
  displayName: 'Print Variables'
  inputs:
    targetType: 'inline'
    script: |
      Get-ChildItem -Path Env: | Sort-Object Name | ForEach-Object {
        Write-Host ("{0} = {1}" -f $_.Name, $_.Value)
      }
      Write-Host "Print Variables End"
