# Azure Pipelines YAML file
# Check for more info https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema-reference
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'README.md'
    - 'src/**/*'

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  displayName: Install packages and generate diagrams
  inputs:
    targetType: 'inline'
    script: |
$folder = "plantuml/"

# Get all .puml files in the folder
$pumlFiles = Get-ChildItem -Path $folder -Filter *.puml

# Loop through the files and create a text file with the same name
foreach ($file in $pumlFiles) {
    $txtFile = $file.FullName -replace "\.puml$", ".txt"
    Write-Host "Creating $txtFile"
    Add-Content -Path $txtFile -Value $file.Name
}

          git config --global user.email "jonas.cahenzli@gmail.com"
          git config --global user.name "generate-UML-images-pipeline"
          git add .
          git commit -m "Add generated diagram for file $file"
          git push origin
