# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - feature/*

pool:
  vmImage: "windows-latest"

steps:
  - task: Cache@2
    inputs:
      key: "gradle | \"$(Agent.OS)\" | **/build/**"
      restoreKeys: "gradle | \"$(Agent.OS)\""
      path: ".gradle"
    displayName: "Cache dependencies and build directory"

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: "17"
      jdkArchitectureOption: "x64"
      jdkSourceOption: "PreInstalled"
    displayName: "Setup JDK 17"

  - task: Gradle@3
    inputs:
      workingDirectory: ""
      gradleWrapperFile: "gradlew.bat"
      gradleOptions: "-Xmx3072m"
      options: "-Pvaadin.productionMode --stacktrace --info"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.17"
      jdkArchitectureOption: "x64"
      publishJUnitResults: true
      testResultsFiles: "**/TEST-*.xml"
      tasks: "build"
    displayName: "Gradle Build"
  
  - task: PushToHeroku@0
    inputs:
      ApiKey: "$(HEROKU_API_KEY)"
      AppName: "$(HEROKU_APP_NAME)"
      PushRoot: "$(System.DefaultWorkingDirectory)"
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/main'))
    displayName: "Deploy to Heroku"