name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'specific'
      project: 'e6858bfb-b65c-4bd5-a31a-631bcc276778'
      definition: '9'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latest'
      artifactName: 'fortylove_releaseCandidate'
      targetPath: '$(Pipeline.Workspace)'
    displayName: "Download Release-Candidate Build Artifact"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Pipeline.Workspace)/fortylove-0.0.1-SNAPSHOT.jar'
      ArtifactName: 'fortylove_release'
      publishLocation: 'Container'
    displayName: "Publish Release Build Artifact"