trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'specific'
      project: 'e6858bfb-b65c-4bd5-a31a-631bcc276778'
      definition: '9'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latest'
      artifactName: 'fortyloveapp'
      targetPath: '$(Pipeline.Workspace)/app'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure subscription 1(1)(f0a71b7c-089b-4b57-9427-2171fc0aee67)'
      appType: 'webAppLinux'
      appName: 'fortylove'
      package: '$(Pipeline.Workspace)/app/fortylove-0.0.1-SNAPSHOT.jar'
      runtimeStack: 'JAVA|17-java17'