# Pipeline to generate PlantUML diagrams
# Build PNG files from PUML
pool:
  vmImage: 'ubuntu-latest'
trigger:
  branches:
    include:
      - feature/*
  paths:
    include:
      - 'documents/design/*'
workspace:
    clean: all
    
steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0
- task: UseNode@1
  displayName: Install Node
  inputs:
    version: '6.x'
- task: Npm@1
  displayName: Install Node Plant UML
  inputs:
    command: 'custom'
    customCommand: 'install node-plantuml -g' 

- task: PowerShell@2
  displayName: Print Variables
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "BUILD_SOURCEBRANCHNAME = $Env:BUILD_SOURCEBRANCHNAME"
      Write-Host "USERPROFILE = $Env:USERPROFILE"

steps:
- script: |
    # Install required packages
    sudo apt-get update
    sudo apt-get install -y graphviz openjdk-8-jre-headless

    # Download and install PlantUML
    curl -L https://sourceforge.net/projects/plantuml/files/plantuml.1.2021.16.jar/download > plantuml.jar
    sudo mv plantuml.jar /usr/local/bin/plantuml.jar
    sudo chmod +x /usr/local/bin/plantuml.jar

    # Generate PlantUML diagrams
    mkdir -p plantuml/generated
    for file in plantuml/*.puml; do
        echo "Generating diagram for file $file"
        java -jar /usr/local/bin/plantuml.jar -tpng "$file" -o plantuml/generated
        # Check in the generated PNG files to the repo
        git add plantuml/generated/*.png
        git commit -m "Add generated diagram for file $file"
    done
  displayName: Generate PlantUML diagrams and check them into the repo
      
- task: PowerShell@2
  displayName: Check Out
  inputs:
    targetType: 'inline'
    script: |
            git config --global user.email "jonas.cahenzli@gmail.com"
            git config --global user.name "generate-UML-images-pipeline"
            git branch
            git status
            Write-Host "checkout branch = feature/$Env:BUILD_SOURCEBRANCHNAME"
            git checkout "feature/$Env:BUILD_SOURCEBRANCHNAME"

- task: PowerShell@2
  displayName: Print All Puml Files
  inputs:
    targetType: 'inline'
    script: |
            $sourceRoot = "$Env:Build.SourcesDirectory"
            Write-Host "sourceRoot $sourceRoot"
            Get-ChildItem $sourceRoot -Recurse -Filter "*.puml" |
                Foreach-Object   {
                    $fileWithPath = $_.Fullname         
                    Write-Host "Puml-File $fileWithPath"
                }


- task: InstallPlantUMLJar
  displayName: Install PlantUML JAR
  inputs:
    targetType: 'inline'
    script: |
      $plantumlVersion = "1.2023.6"
      $plantumlUrl = "https://sourceforge.net/projects/plantuml/files/$plantumlVersion/plantuml.$plantumlVersion.jar/download"
      $plantumlPath = "$Env:USERPROFILE\.plantuml\plantuml.jar"
      Write-Host "JarfileUp = $plantumlPath"
      if(!(Test-Path -Path $plantumlPath)) {
        New-Item -ItemType Directory -Force -Path $Env:USERPROFILE\.plantuml
        Invoke-WebRequest -Uri $plantumlUrl -OutFile $plantumlPath
      }
  outputs:
   jarPath: $plantumlPath

- task: PowerShell@2
  displayName: Build Images
  inputs:
    targetType: 'inline'
    script: |
            $sourceRoot = "$Env:Build.SourcesDirectory"
            Get-ChildItem $sourceDir -Recurse -Filter "*.puml" |
                Foreach-Object   {
                    $fileWithPath = $_.Fullname       
                    $png =  Join-Path  -Path $_.DirectoryName -ChildPath ("{0}.png" -f $_.Basename ) 
                    $execute = "puml generate $fileWithPath -o $png "; 
                    Invoke-Expression -Command $execute 
                }

- task: PowerShell@2
  displayName: Build Images with plantUML jar
  dependsOn: InstallPlantUMLJar
  inputs:
    targetType: 'inline'
    myJarPath:  $[ dependencies.InstallPlantUMLJar.outputs['jarPath'] ]
    script: |
      $sourceDir = "$Env:BUILD_SOURCESDIRECTORY"
      Write-Host "JarfilePassedDown = $myJarPath"
      Get-ChildItem $sourceDir -Recurse -Filter "*.puml" | ForEach-Object {
        $pumlFilePath = $_.FullName
        $pngFilePath = $_.DirectoryName + "\" + $_.BaseName + ".png"
        Write-Host "Converting $pumlFilePath to $pngFilePath ..."
        java -jar $myJarPath $pumlFilePath -o $pngFilePath 
      }
  env:
    JAVA_HOME: $(JAVA_HOME)


- task: PowerShell@2
  displayName: Check In
  inputs:
    targetType: 'inline'
    script: |
            git add --all
            git commit -m "$Env:BUILD_BUILDNUMBER [skip ci]"
            #git checkout "$Env:BUILD_SOURCEBRANCHNAME"
            #git merge "$Env:BUILD_SOURCEBRANCHNAME" -m "$Env:BUILD_BUILDNUMBER"
            #git branch -d "$Env:BUILD_BUILDNUMBER"
            git push origin 
          
