trigger:
  branches:
    include:
      - feature/*

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Cache@2
    inputs:
      key: "gradle | \"$(Agent.OS)\" | **/build/**"
      restoreKeys: "gradle | \"$(Agent.OS)\""
      path: ".gradle"
    displayName: "Cache dependencies and build directory"

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: "17"
      jdkArchitectureOption: "x64"
      jdkSourceOption: "PreInstalled"
    displayName: "Setup JDK 17"

  - task: Gradle@3
    inputs:
      workingDirectory: ""
      gradleWrapperFile: "gradlew"
      gradleOptions: "-Xmx3072m"
      options: "-Pvaadin.productionMode --stacktrace --info"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.17"
      jdkArchitectureOption: "x64"
      publishJUnitResults: true
      testResultsFiles: "**/TEST-*.xml"
      tasks: "build"
    env:
      SPRING_DATASOURCE_URL: "$(SPRING_DATASOURCE_URL)"
      SPRING_DATASOURCE_USERNAME: "$(SPRING_DATASOURCE_USERNAME)"
      SPRING_DATASOURCE_PASSWORD: "$(SPRING_DATASOURCE_PASSWORD)"
    displayName: "Gradle Build"

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure subscription 1(1)(f0a71b7c-089b-4b57-9427-2171fc0aee67)'
      appType: 'webAppLinux'
      appName: 'fortylove'
      package: '$(System.DefaultWorkingDirectory)/build/libs/fortylove-0.0.1-SNAPSHOT.jar'
      runtimeStack: 'JAVA|17-java17'