name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: PowerShell@2
    inputs:
      targetType: "inline"
      script: |
        Write-Host "======================================================================="
        Write-Host "PRINTING VARIABLES"
        Write-Host "======================================================================="
        Write-Host "Build.SourceBranch: $(Build.SourceBranch)"
        Write-Host "======================================================================="
    displayName: "Print Deployment Variables"

  - task: DownloadPipelineArtifact@2
    env:
      ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
        ARTIFACT_NAME: "fortylove_main"
      ${{ elseif eq(eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
        ARTIFACT_NAME: "fortylove_develop"
    inputs:
      buildType: "specific"
      project: "e6858bfb-b65c-4bd5-a31a-631bcc276778"
      definition: "9"
      specificBuildWithTriggering: true
      buildVersionToDownload: "latest"
      artifactName: $(ARTIFACT_NAME)
      targetPath: "$(Pipeline.Workspace)"
    displayName: "Download $(artifactName) Build Artifact"

  - task: AzureWebApp@1
    inputs:
      azureSubscription: "Azure subscription 1(1)(f0a71b7c-089b-4b57-9427-2171fc0aee67)"
      appType: "webAppLinux"
      appName: "fortylove"
      package: "$(Pipeline.Workspace)/fortylove-0.0.1-SNAPSHOT.jar"
      runtimeStack: "JAVA|17-java17"