@startuml
object UC_1 {
<#lightblue,#black>|= Name |<#white> Tennisplatz reservieren |
<#lightblue,#black>|= Ziel im Kontext |<#white> Ein User reserviert einen Tennisplatz |
<#lightblue,#black>|= Kurzbeschreibung |<#white> Ein User sucht sich einen freien Zeitslot, waehlt einen weiteren User (Spielpartner) aus mit welchem die Reservation getaetigt wird.  |
<#lightblue,#black>|= Vorbedingungen |<#white> - User hat ein Login\n - User hat ausreichen "Kontigent / Budget" foer die gewoenschte Platzreservation\n - Spielpartner-User hat ausreichend "Kontigent / Budget" foer die gewoenschte Platzreservation\n - Freie Plaetze sind vorhanden  |
<#lightblue,#black>|= Akteure |<#white> - User 1 (der der die Reservation taetig)\n - User 2 (der Spielpartner-User) |
<#lightblue,#black>|= Trigger |<#white> User taetigt eine Reservation  |
<#lightblue,#black>|= Essenzielle Schritte |<#white> 1. User waehlt freien Zeitslot aus\n\t-> Reaktion des Systems: List mit verfoegbaren User (Spielpartner-User) wird zur Auswahl bereitgestellt\n 2. User waehlt gewoenschten Spielpartner-User aus und bestaetigt Reservation\n\t-> Reaktion des Systems: Reservation wird im System registriert  |
<#lightblue,#black>|= Erweiterungen |<#white> 2a. System stellt fest, dass User 1 oder User 2 zu wenig "Kontigent / Budget" hat\n 2b. System informiert User oeber zu wenig "Kontigent / Budget" und lehnt Reservationsanfrage ab |
<#lightblue,#black>|= Nachbedingungen |<#white> - User 1 und User 2 erhalten Reservationsbestaetigung\n - Reservation ist im System sichtbar\n - Reservierter Platz ist foer weitere Reservation nicht mehr erhaeltlich\n - "Kontigent / Budget" Konto der beiden User wird aktuallisiert |
<#lightblue,#black>|= Fragen, Kommentare |<#with> - Wie sollen die beiden User eine Reservationsbestaetigung erhalten?\n\t-> per Mail?\n\t-> per SMS?\n\t-> per WhatsApp?\n\t-> per App? |
}

object UC_2 {
<#lightblue,#black>|= Name|<#white> Platzbelegung anzeigen |
<#lightblue,#black>|= Ziel im Kontext |<#white> User sehen die Status der Plaetze eines Clubs  |
<#lightblue,#black>|= Kurzbeschreibung |<#white> Ein User navigiert zur Seite, auf welcher die Plaetze des Clubs angezeigt werden.\n Die Status der Plaetze werden pro Zeitslot angezeigt.  |
<#lightblue,#black>|= Vorbedingungen |<#white> - User hat ein Login\n - User gehoert einem Club an\n - Club besitzt Plaetze  |
<#lightblue,#black>|= Akteure |<#white> User |
<#lightblue,#black>|= Trigger |<#white> User moechte sich einen oeberblick der aktuellen Platzauslastung machen |
<#lightblue,#black>|= Essenzielle Schritte |<#white> 1. User loggt sich ein\n 2. User navigiert zur Platzoebersichts Ansicht  |
<#lightblue,#black>|= Erweiterungen |<#white> 1.5 User navigiert zu gewoenschtem Verein\n |
<#lightblue,#black>|= Nachbedingungen |<#white> keine |
<#lightblue,#black>|= Fragen, Kommentare |<#white> - Loggt man sich auf einen Verein ein oder auf die App auf welcher dann mehrer Verein ersichtlich sind? |
}

@enduml