@startuml
object UC_1 {
<#lightblue,#black>|= Name |<#white> Tennisplatz reservieren |
<#lightblue,#black>|= Ziel im Kontext |<#white>  |
<#lightblue,#black>|= Kurzbeschreibung |<#white>  |
<#lightblue,#black>|= Vorbedingungen |<#white>  |
<#lightblue,#black>|= Akteure |<#white>  |
<#lightblue,#black>|= Trigger |<#white>  |
<#lightblue,#black>|= Essenzielle Schritte |<#white>  |
<#lightblue,#black>|= Erweiterungen |<#white>  |
<#lightblue,#black>|= Nachbedingungen |<#white>  |
<#lightblue,#black>|= Fragen, Kommentare |<#white>  |
}

object UC_2 {
<#lightblue,#black>|= Name|<#white> Platzbelegung anzeigen |
<#lightblue,#black>|= Ziel im Kontext |<#white>  |
<#lightblue,#black>|= Kurzbeschreibung |<#white>  |
<#lightblue,#black>|= Vorbedingungen |<#white>  |
<#lightblue,#black>|= Akteure |<#white>  |
<#lightblue,#black>|= Trigger |<#white>  |
<#lightblue,#black>|= Essenzielle Schritte |<#white>  |
<#lightblue,#black>|= Erweiterungen |<#white>  |
<#lightblue,#black>|= Nachbedingungen |<#white>  |
<#lightblue,#black>|= Fragen, Kommentare |<#white>  |
}

@enduml