@startuml
left to right direction
actor "Member" as Actor
rectangle fortylove {
    Actor --> (UC_1\nTennisplatz reservieren)
    Actor --> (UC_2\nPlatzbelegung anzeigen)
    Actor --> (Reservierung loeschen)
    Actor --> (oebersicht der Reservierungen anzeigen)
    Actor --> (Reservierung bearbeiten)
    Actor --> (Statistik anzeigen)
    Actor --> (Buchungsontingent anzeigen)
    Actor --> (Eigenes Profil anzeigen)
    Actor --> (Favoriten erstellen)
    Actor --> (Anfrage foer Clubbeitritt stellen)
}

@enduml

