@startuml
left to right direction
actor "Guest" as Actor
rectangle fortylove {
    Actor --> (Tennisplatz reservieren)
    Actor --> (Reservierung loeschen)
    Actor --> (Uebersicht der Reservierungen anzeigen)
    Actor --> (Platzbelegung anzeigen)
    Actor --> (Reservierungen bearbeiten)
}

@enduml

