@startuml
left to right direction
actor "Admin" as Actor
rectangle fortylove {
    Actor --> (Tennisplaetze erstellen)
    Actor --> (Tennisplaetze loeschen)
    Actor --> (Tennisplaetze konfigurieren)
    Actor --> (User verwalten)
}

@enduml

