@startuml
left to right direction
actor "Guest" as Actor
rectangle fortylove {
    Actor --> (Tennisplatz reservieren)
    Actor --> (Reservierung löschen)
    Actor --> (Übersicht der Reservierungen anzeigen)
    Actor --> (Platzbelegung anzeigen)
    Actor --> (Reservierung bearbeiten)
}

@enduml

