@startuml
object Projekt_Risikoanalyse {
<#orange>|= Risiko |= <#orange> Schaden \n 1-10 |= <#orange> Eintretens-\n wahrscheinlichkeit \n 1-10 |= <#orange> Risikoindex \n 1-100 |= <#orange> Begruendung |= <#orange> Checkpoints |= <#orange> Massnahmen  |
| Keine Akzeptanz der Endbenutzer | 7 |  3 | 21 | 1. Endbenutzer sehen keinen Vorteil dem Konkurenzapp gegenueber \n 2. Platzbuchnungsprozess zu umstaendlich\n 3. App zu langsam   | 1. keine - Endbentzer darf keinen Nachteil wahrnehmen \n 2a. Weniger oder gleich viele Klicks bis zur Platzbuchung wie bestehende Loesung \n 2b. Zeitaufwand <= bestehende Loesung  \n 3. Appbenutzung muss fluessig laufen | - 10 Powerusers einbeziehen \n - frueh Userfeedbacks einholen mit UI Prototyp / MVP |
| Keine Akzeptanz der Vereinsfuehrung | 10 | 3 | 30 | 1. Loesung unterscheidet sich preislich zu wenig von den Konkurenzloesungen \n 2. Transfer auf neue Loesung ist zu umstaendlich \n 3. Wartung / Betrieb zu umstaendlich\n 4. Loesung nicht zuverlaessig  | 1. Loesung kostet im Unterhalt < 1/10\n 2. < 4- Mann-Stunden Aufwand\n 3. Managbar durch eine im Verein ehrenamtlich arbeitetende Person \n 4. Downtime waehrend buchbaren Zeiten < 1%  | - Vorstand einbeziehen\n - frueh Feedback einholen anhand Prozessablaeufe\n - transparente Kostenauflistung |
}

@enduml