@startuml
object UC_1 {
<#lightblue,#black>|= Name |<#white> Tennisplatz reservieren |
<#lightblue,#black>|= Ziel im Kontext |<#white> Ein Member reserviert einen Tennisplatz |
<#lightblue,#black>|= Kurzbeschreibung |<#white> Ein Member sucht sich einen freien Zeitslot, wählt einen weiteren Member (Spielpartner) aus mit welchem die Reservation getätigt wird.  |
<#lightblue,#black>|= Vorbedingungen |<#white> - Member hat ein Login\n - Member hat ausreichen "Kontigent / Budget" für die gewünschte Platzreservation\n - Spielpartner-Member hat ausreichend "Kontigent / Budget" für die gewünschte Platzreservation\n - Freie Plätze sind vorhanden  |
<#lightblue,#black>|= Akteure |<#white> - Member 1 (der der die Reservation tätig)\n - Member 2 (der Spielpartner-Member) |
<#lightblue,#black>|= Trigger |<#white> Member tätigt eine Reservation  |
<#lightblue,#black>|= Essenzielle Schritte |<#white> 1. Member wählt freien Zeitslot aus\n\t-> Reaktion des Systems: List mit verfügbaren Member (Spielpartner-Member) wird zur Auswahl bereitgestellt\n 2. Member wählt gewünschten Spielpartner-Member aus und bestätigt Reservation\n\t-> Reaktion des Systems: Reservation wird im System registriert  |
<#lightblue,#black>|= Erweiterungen |<#white> 2a. System stellt fest, dass Member 1 oder Member 2 zu wenig "Kontigent / Budget" hat\n 2b. System informiert Member über zu wenig "Kontigent / Budget" und lehnt Reservationsanfrage ab |
<#lightblue,#black>|= Nachbedingungen |<#white> - Member 1 und Member 2 erhalten Reservationsbestätigung\n - Reservation ist im System sichtbar\n - Reservierter Platz ist für weitere Reservation nicht mehr erhältlich\n - "Kontigent / Budget" Konto der beiden Member wird aktuallisiert |
<#lightblue,#black>|= Fragen, Kommentare |<#with> - Wie sollen die beiden Member eine Reservationsbestätigung erhalten?\n\t-> per Mail?\n\t-> per SMS?\n\t-> per WhatsApp?\n\t-> per App? |
}

object UC_2 {
<#lightblue,#black>|= Name|<#white> Platzbelegung anzeigen |
<#lightblue,#black>|= Ziel im Kontext |<#white> Member sehen die Status der Plätze eines Clubs  |
<#lightblue,#black>|= Kurzbeschreibung |<#white> Ein Member navigiert zur Seite, auf welcher die Plätze des Clubs angezeigt werden.\n Die Status der Plätze werden pro Zeitslot angezeigt.  |
<#lightblue,#black>|= Vorbedingungen |<#white> - Member hat ein Login\n - Member gehört einem Club an\n - Club besitzt Plätze  |
<#lightblue,#black>|= Akteure |<#white> Member |
<#lightblue,#black>|= Trigger |<#white> Member möchte sich einen Überblick der aktuellen Platzauslastung machen |
<#lightblue,#black>|= Essenzielle Schritte |<#white> 1. Member loggt sich ein\n 2. Member navigiert zur Platzübersichts Ansicht  |
<#lightblue,#black>|= Erweiterungen |<#white> 1.5 Member navigiert zu gewünschtem Verein\n |
<#lightblue,#black>|= Nachbedingungen |<#white> keine |
<#lightblue,#black>|= Fragen, Kommentare |<#white> - Loggt man sich auf einen Verein ein oder auf die App auf welcher dann mehrer Verein ersichtlich sind? |
}

@enduml